// Generated by scripts/gen-examples.mjs from live responses on 2026-09-27.
// Real shapes, trimmed (arrays and zone/metric maps cut to 2 entries). Re-run after changing a response shape.
export const EXAMPLES: Record<string, any> = {
  "snapshot": {
    "generated": 1790496358,
    "zones": {
      "GB": {
        "zone": "GB",
        "metrics": {
          "demand": {
            "value": 20878,
            "unit": "MW",
            "ts": 1790494200,
            "resolution": "30m"
          },
          "price": {
            "value": 141.97,
            "unit": "GBP/MWh",
            "ts": 1790467200,
            "resolution": "30m"
          }
        },
        "updated": 1790496352,
        "attribution": "Supported by National Energy SO Open Data",
        "license": "NESO-Open-Licence"
      },
      "DE-LU": {
        "zone": "DE-LU",
        "metrics": {
          "demand": {
            "value": 43724.47645,
            "unit": "MW",
            "ts": 1790492400,
            "resolution": "15m"
          },
          "price": {
            "value": 192.3,
            "unit": "EUR/MWh",
            "ts": 1790631900,
            "resolution": "15m"
          }
        },
        "updated": 1790496275,
        "attribution": "Data: ENTSO-E Transparency Platform",
        "license": "CC-BY-4.0"
      }
    }
  },
  "brief": {
    "zone": "GB",
    "zone_name": "Great Britain",
    "as_of": 1790496611,
    "current": {
      "demand": {
        "value": 20878,
        "unit": "MW",
        "ts": 1790494200
      },
      "price": {
        "value": 141.97,
        "unit": "GBP/MWh",
        "ts": 1790467200
      }
    },
    "context": {
      "price": {
        "percentile": 43,
        "vs_median_pct": -2.9,
        "median": 146.23,
        "min": -23.28,
        "max": 246.58,
        "sample_count": 1424,
        "window_days_actual": 29.6,
        "unit": "GBP/MWh"
      }
    },
    "context_window_requested_days": 30,
    "summary": "For Great Britain, price is typical (43rd percentile over the last 29.6 days); carbon intensity is typical (34th percentile); demand is typical; wind is the largest generation source at 54.3% of the mix.",
    "coverage_note": "Context blocks are omitted for metrics this zone doesn't publish or where fewer than 20 samples exist. window_days_actual reflects the real data span, which varies by zone and metric. \"current\" is the most recent point at or before reque...",
    "attribution": "Supported by National Energy SO Open Data",
    "license": "NESO-Open-Licence"
  },
  "latest": {
    "zone": "GB",
    "metrics": {
      "demand": {
        "value": 20878,
        "unit": "MW",
        "ts": 1790494200,
        "resolution": "30m"
      },
      "price": {
        "value": 141.97,
        "unit": "GBP/MWh",
        "ts": 1790467200,
        "resolution": "30m"
      }
    },
    "updated": 1790496352,
    "attribution": "Supported by National Energy SO Open Data",
    "license": "NESO-Open-Licence"
  },
  "history": {
    "zone": "GB",
    "metric": "price",
    "start": 1790410212,
    "end": 1790496612,
    "count": 32,
    "attribution": "Supported by National Energy SO Open Data",
    "license": "NESO-Open-Licence",
    "data": [
      {
        "metric": "price",
        "fuel": "",
        "ts": 1790411400,
        "value": 94.98,
        "unit": "GBP/MWh",
        "resolution": "30m",
        "source": "elexon"
      },
      {
        "metric": "price",
        "fuel": "",
        "ts": 1790413200,
        "value": 73.93,
        "unit": "GBP/MWh",
        "resolution": "30m",
        "source": "elexon"
      }
    ]
  },
  "zones": {
    "zones": [
      {
        "id": "US-CAISO",
        "name": "California ISO",
        "source": "eia",
        "tz": "America/Los_Angeles",
        "currency": "USD",
        "license": "public-domain",
        "attribution": "Source: U.S. Energy Information Administration"
      },
      {
        "id": "US-ERCOT",
        "name": "ERCOT (Texas)",
        "source": "eia",
        "tz": "America/Chicago",
        "currency": "USD",
        "license": "public-domain",
        "attribution": "Source: U.S. Energy Information Administration"
      }
    ]
  },
  "status": {
    "now": 1790496612,
    "sources": [
      {
        "source": "aemo",
        "zone": "AU-NSW",
        "last_ok": 1790496356,
        "last_error": ""
      },
      {
        "source": "aemo",
        "zone": "AU-QLD",
        "last_ok": 1790496356,
        "last_error": ""
      }
    ]
  }
};
